CREATE DATABASE CRUDPDO;
USE CRUDPDO;

CREATE TABLE pessoa(
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    telefone VARCHAR(15) NOT NULL,
    email VARCHAR(100) NOT NULL
);
